/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/auth/token": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** @description Get a JWT token using an API key */
		post: operations["postApiAuthToken"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** @description Refresh JWT token using existing valid token */
		post: operations["postApiAuthRefresh"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/users": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Get list of all users (admin only) */
		get: operations["getApiAdminUsers"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/deploy/deploy": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** @description Deploy the latest version of the application */
		post: operations["postApiDeployDeploy"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/content/detail/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Get content details */
		get: operations["getApiContentDetail:id"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: never;
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	postApiAuthToken: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful response with JWT token */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						access_token: string;
						/** @constant */
						token_type: "Bearer";
						expires_in: number;
						client_name?: string;
					};
				};
			};
		};
	};
	postApiAuthRefresh: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful response with new JWT token */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						access_token: string;
						/** @constant */
						token_type: "Bearer";
						expires_in: number;
						client_name?: string;
					};
				};
			};
		};
	};
	getApiAdminUsers: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful response with list of users */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						users: {
							id: number;
							name: string;
							email: string;
						}[];
						client: string;
						timestamp: string;
					};
				};
			};
		};
	};
	postApiDeployDeploy: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": {
					owner: string;
					repo: string;
					event_type: string;
				};
			};
		};
		responses: {
			/** @description Successful response with deployment status */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						message: string;
						status: string;
					};
				};
			};
			/** @description Failed to trigger deployment */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						error: string;
					};
				};
			};
		};
	};
	"getApiContentDetail:id": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful response with content details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						title: string;
						content: string;
					};
				};
			};
			/** @description Failed to get content details */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						error: string;
					};
				};
			};
		};
	};
}
