name: CMS Webhook Subscribe Deploy
on:
  # necessary for integration with CMS
  repository_dispatch:
    # event_type must match the value configured in the CMS
    types: [cms-content-update]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          CMS_URL: ${{ env.CMS_URL }}
          READ_API_KEY: ${{ secrets.READ_API_KEY }}
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          env: |
            CMS_URL
          secrets: |
            READ_API_KEY
        env:
          CMS_URL: ${{ env.CMS_URL }}
          READ_API_KEY: ${{ secrets.READ_API_KEY }}
